// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIqODLrb0lmUad59VuQGO0xg6R3I5itgA',
    appId: '1:922344240132:web:9853d636344f18a9077151',
    messagingSenderId: '922344240132',
    projectId: 'tourism-97339',
    authDomain: 'tourism-97339.firebaseapp.com',
    storageBucket: 'tourism-97339.appspot.com',
    measurementId: 'G-HTDH9VE371',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOAqxHMOp1UhZjCSU4NiHi7el2Spb0dLQ',
    appId: '1:922344240132:android:c987c3d3404ecf68077151',
    messagingSenderId: '922344240132',
    projectId: 'tourism-97339',
    storageBucket: 'tourism-97339.appspot.com',
  );

}